import { Artist } from "./types";

//The instance data
export const artistsData: Artist[] = [
  {
    id: 1,
    name: "2Holis",
    genre: "HyperPop",
    image: "/photos/2Holis.webp",
    bio: "Amreican hyper pop artist",
    popularity: 9,
  },
  {
    id: 2,
    name: "Ye",
    genre: "hiphop",
    image: "/photos/Ye-def.webp",
    bio: "GOAT",
    popularity: 10,
  },
  {
    id: 3,
    name: "Hamdi",
    genre: "UKB",
    image: "/photos/hamdi.webp",
    bio: "Iconic artist in UKB scene",
    popularity: 6,
  },
  {
    id: 4,
    name: "Sammy Virji",
    genre: "UKG",
    image: "/photos/sammyvirji.webp",
    bio: "UKG = Sammy Virji",
    popularity: 7,
  },
  {
    id: 5,
    name: "Drake",
    genre: "hiphop",
    image: "/photos/drake.jpg",
    bio: "Canadian rapper, one of the best-selling artists.",
    popularity: 10,
  },
  {
    id: 6,
    name: "Borne",
    genre: "DUb",
    image: "/photos/borne.webp",
    bio: "Canadian UKB artist",
    popularity: 4,
  },
  {
    id: 7,
    name: "Fred again",
    genre: "dub",
    image: "/photos/Fred.jpeg",
    bio: "World wide artist of UKB, Dub, espically House scene",
    popularity: 10,
  },
  {
    id: 8,
    name: "MPH",
    genre: "UKG",
    image: "/photos/mph.webp",
    bio: "Great figure of UKG, Speed garage.",
    popularity: 4,
  },
  {
    id: 9,
    name: "Oppidan",
    genre: "UKG",
    image: "/photos/oppidan.webp",
    bio: "British UKG/Speed garage artist. Her music is so groovy",
    popularity: 5,
  },
  {
    id: 10,
    name: "MF Doom",
    genre: "hiphop",
    image: "/photos/doom.jpeg",
    bio: "British singer known for her powerful voice and emotional ballads.",
    popularity: 8,
  },
  {
    id: 11,
    name: "Cesco",
    genre: "UKB",
    image: "/photos/cesco.webp",
    bio: "British singer known for her powerful voice and emotional ballads.",
    popularity: 3,
  },
  {
    id: 12,
    name: "Ternion Sound",
    genre: "dub",
    image: "/photos/ternion.webp",
    bio: "British singer known for her powerful voice and emotional ballads.",
    popularity: 2,
  },
];